services:
#    sf_web_app_back_office.example:
#        class: SfWebApp\BackOfficeBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
# SECURITY
sf_web_app_back_office_security:
    resource: "@SfWebAppBackOfficeBundle/Resources/config/routing/security.yml"

# BACKOFFICE
sf_web_app_back_office_bo:
    resource: "@SfWebAppBackOfficeBundle/Resources/config/routing/backoffice.yml"